module.exports = {
  blogs: [
    {
      blogType: 'technical blogs',
      details: [
        {
          name: 'Class and ID selectors',
          date: '10 February 2022',
          image:
            'https://miro.medium.com/max/1400/1*qZk0Zee2kLp0fis1eoF_Hg.jpeg',
          shortPost:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. In hac habitasse platea dictumst.',
          post: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
          ],
        },
        {
          name: 'Problem Solving',
          date: '11 February 2022',
          image:
            'https://media.npr.org/assets/img/2017/06/03/gettyimages-453879976-59801bc8f1f6bda5175c3098bb0d9a28696394be.jpg',
          shortPost:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. In hac habitasse platea dictumst.',
          post: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
          ],
        },
      ],
    },
    {
      blogType: 'personal blogs',
      details: [
        {
          name: 'Neuroplasticity & Growth',
          date: '14 February 2022',
          image: 'https://i.imgur.com/kQ1cS4a.jpg',
          shortPost:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. In hac habitasse platea dictumst.',
          post: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
          ],
        },
        {
          name: 'Learning Plan',
          date: '15 February 2022',
          image:
            'https://fitsmallbusiness.com/wp-content/uploads/2019/10/FeatureImage_How_to_Write_a_Business_Plan.jpg',
          shortPost:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. In hac habitasse platea dictumst.',
          post: [
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed venenatis ligula ut nunc malesuada, pharetra molestie mi varius. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed sit amet semper magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur lobortis sapien nec est pulvinar, ut molestie ipsum dignissim. Mauris a tortor nibh. Vivamus at turpis posuere ex tincidunt lacinia. Donec at nunc tempus, imperdiet tortor suscipit, gravida lectus. Integer blandit nisl id nisl tristique, vitae egestas libero efficitur. Praesent hendrerit, purus in rhoncus sollicitudin, massa nibh posuere dolor, egestas rhoncus turpis nisl eu sapien. Pellentesque nunc justo, aliquam in pellentesque in, cursus sed lectus. Donec aliquam maximus ultricies. In hac habitasse platea dictumst. Vivamus eget sem ullamcorper, venenatis tellus nec, pharetra sem.',
          ],
        },
      ],
    },
  ],
}
